FROM node:24-alpine
WORKDIR /usr/src/app

ENV NODE_ENV=development
# tetap set variabel manual meskipun sudah ada di .env karena docker-compose tidak bisa membaca .env di dalam container karena beda lifecycle.

# Mengopi package.json untuk proses build awal
COPY package*.json ./
# Menginstall library dasar ke dalam image (sebagai cache awal)
RUN npm install

EXPOSE 3000